<script setup>
 import DefaultPage from '@/components/DefaultPage.vue'
 import Table from '@/components/Table.vue'
 import Button from '@/components/Button.vue'
  import icons from "@/utils/icons";
import { ref } from 'vue';
import Status_row from '../components/statusRow.vue';
import { openModal } from "@customizer/modal-x";  
  const entries = ref([
  {
    firstName: "Abebe",
	fathersName: "beso",
    grandFathersName: "bela",
    InspectionDate: "05-08-2024",
    VehicleDetail: "Toyota Yaris 2004 - Code 3",
    Insurance: "Nyala Insurance",
    Premium: "ETB 3,400",
	status: "Not Checked",
  },
  {
    firstName: "Abebe",
    fathersName: "beso",
    grandFathersName: "bela",
    InspectionDate: "05-08-2024",
    VehicleDetail: "Toyota Yaris 2004 - Code 3",
    Insurance: "Nyala Insurance",
    Premium: "ETB 3,400",
	status: "Not Checked",
  },
  {
    firstName: "Abebe",
    fathersName: "beso",
    grandFathersName: "bela",
    InspectionDate: "05-08-2024",
    VehicleDetail: "Toyota Yaris 2004 - Code 3",
    Insurance: "Nyala Insurance",
    Premium: "ETB 3,400",
	status: "Checked",
  },
  {
    firstName: "Abebe",
    fathersName: "beso",
    grandFathersName: "bela",
    InspectionDate: "05-08-2024",
    VehicleDetail: "Toyota Yaris 2004 - Code 3",
    Insurance: "Nyala Insurance",
    Premium: "ETB 3,400",
	status: "Not Checked",
  },
  {
    firstName: "Abebe",
    fathersName: "beso",
    grandFathersName: "bela",
    InspectionDate: "05-08-2024",
    VehicleDetail: "Toyota Yaris 2004 - Code 3",
    Insurance: "Nyala Insurance",
    Premium: "ETB 3,400",
	status: "Not Checked",
  },
  {
    firstName: "Abebe",
    fathersName: "beso",
    grandFathersName: "bela",
    InspectionDate: "05-08-2024",
    VehicleDetail: "Toyota Yaris 2004 - Code 3",
    Insurance: "Nyala Insurance",
    Premium: "ETB 3,400",
	status: "Checked",
  },
  {
    firstName: "Abebe",
    fathersName: "beso",
    grandFathersName: "bela",
    InspectionDate: "05-08-2024",
    VehicleDetail: "Toyota Yaris 2004 - Code 3",
    Insurance: "Nyala Insurance",
    Premium: "ETB 3,400",
	status: "Not Checked",
  },
  {
    firstName: "Abebe",
    fathersName: "beso",
    grandFathersName: "bela",
    InspectionDate: "05-08-2024",
    VehicleDetail: "Toyota Yaris 2004 - Code 3",
    Insurance: "Nyala Insurance",
    Premium: "ETB 3,400",
	status: "Not Checked",
  },
  {
    firstName: "Abebe",
    fathersName: "beso",
    grandFathersName: "bela",
    InspectionDate: "05-08-2024",
    VehicleDetail: "Toyota Yaris 2004 - Code 3",
    Insurance: "Nyala Insurance",
    Premium: "ETB 3,400",
	status: "Not Checked",
  },
  {
    firstName: "Abebe",
    fathersName: "beso",
    grandFathersName: "bela",
    InspectionDate: "05-08-2024",
    VehicleDetail: "Toyota Yaris 2004 - Code 3",
    Insurance: "Nyala Insurance",
    Premium: "ETB 3,400",
	status: "Not Checked",
  },
  {
    firstName: "Abebe",
    fathersName: "beso",
    grandFathersName: "bela",
    InspectionDate: "05-08-2024",
    VehicleDetail: "Toyota Yaris 2004 - Code 3",
    Insurance: "Nyala Insurance",
    Premium: "ETB 3,400",
	status: "Not Checked",
  },
  {
    firstName: "Abebe",
    fathersName: "beso",
    grandFathersName: "bela",
    InspectionDate: "05-08-2024",
    VehicleDetail: "Toyota Yaris 2004 - Code 3",
    Insurance: "Nyala Insurance",
    Premium: "ETB 3,400",
	status: "Not Checked",
  },
  {
    firstName: "Abebe",
	fathersName: "beso",
    grandFathersName: "bela",
    InspectionDate: "05-08-2024",
    VehicleDetail: "Toyota Yaris 2004 - Code 3",
    Insurance: "Nyala Insurance",
    Premium: "ETB 3,400",
	status: "Not Checked",
  },
  {
    firstName: "Abebe",
    fathersName: "beso",
    grandFathersName: "bela",
    InspectionDate: "05-08-2024",
    VehicleDetail: "Toyota Yaris 2004 - Code 3",
    Insurance: "Nyala Insurance",
    Premium: "ETB 3,400",
	status: "Not Checked",
  },
  {
    firstName: "Abebe",
    fathersName: "beso",
    grandFathersName: "bela",
    InspectionDate: "05-08-2024",
    VehicleDetail: "Toyota Yaris 2004 - Code 3",
    Insurance: "Nyala Insurance",
    Premium: "ETB 3,400",
	status: "Checked",
  },
  {
    firstName: "Abebe",
    fathersName: "beso",
    grandFathersName: "bela",
    InspectionDate: "05-08-2024",
    VehicleDetail: "Toyota Yaris 2004 - Code 3",
    Insurance: "Nyala Insurance",
    Premium: "ETB 3,400",
	status: "Not Checked",
  },
  {
    firstName: "Abebe",
    fathersName: "beso",
    grandFathersName: "bela",
    InspectionDate: "05-08-2024",
    VehicleDetail: "Toyota Yaris 2004 - Code 3",
    Insurance: "Nyala Insurance",
    Premium: "ETB 3,400",
	status: "Not Checked",
  },
  {
    firstName: "Abebe",
    fathersName: "beso",
    grandFathersName: "bela",
    InspectionDate: "05-08-2024",
    VehicleDetail: "Toyota Yaris 2004 - Code 3",
    Insurance: "Nyala Insurance",
    Premium: "ETB 3,400",
	status: "Checked",
  },
  {
    firstName: "Abebe",
    fathersName: "beso",
    grandFathersName: "bela",
    InspectionDate: "05-08-2024",
    VehicleDetail: "Toyota Yaris 2004 - Code 3",
    Insurance: "Nyala Insurance",
    Premium: "ETB 3,400",
	status: "Not Checked",
  },
  {
    firstName: "Abebe",
    fathersName: "beso",
    grandFathersName: "bela",
    InspectionDate: "05-08-2024",
    VehicleDetail: "Toyota Yaris 2004 - Code 3",
    Insurance: "Nyala Insurance",
    Premium: "ETB 3,400",
	status: "Not Checked",
  },
  {
    firstName: "Abebe",
    fathersName: "beso",
    grandFathersName: "bela",
    InspectionDate: "05-08-2024",
    VehicleDetail: "Toyota Yaris 2004 - Code 3",
    Insurance: "Nyala Insurance",
    Premium: "ETB 3,400",
	status: "Not Checked",
  },
  {
    firstName: "Abebe",
    fathersName: "beso",
    grandFathersName: "bela",
    InspectionDate: "05-08-2024",
    VehicleDetail: "Toyota Yaris 2004 - Code 3",
    Insurance: "Nyala Insurance",
    Premium: "ETB 3,400",
	status: "Not Checked",
  },
  {
    firstName: "Abebe",
    fathersName: "beso",
    grandFathersName: "bela",
    InspectionDate: "05-08-2024",
    VehicleDetail: "Toyota Yaris 2004 - Code 3",
    Insurance: "Nyala Insurance",
    Premium: "ETB 3,400",
	status: "Not Checked",
  },
  {
    firstName: "Abebe",
    fathersName: "beso",
    grandFathersName: "bela",
    InspectionDate: "05-08-2024",
    VehicleDetail: "Toyota Yaris 2004 - Code 3",
    Insurance: "Nyala Insurance",
    Premium: "ETB 3,400",
	status: "Not Checked",
  },
  {
    firstName: "Abebe",
	fathersName: "beso",
    grandFathersName: "bela",
    InspectionDate: "05-08-2024",
    VehicleDetail: "Toyota Yaris 2004 - Code 3",
    Insurance: "Nyala Insurance",
    Premium: "ETB 3,400",
	status: "Not Checked",
  },
  {
    firstName: "Abebe",
    fathersName: "beso",
    grandFathersName: "bela",
    InspectionDate: "05-08-2024",
    VehicleDetail: "Toyota Yaris 2004 - Code 3",
    Insurance: "Nyala Insurance",
    Premium: "ETB 3,400",
	status: "Not Checked",
  },
  {
    firstName: "Abebe",
    fathersName: "beso",
    grandFathersName: "bela",
    InspectionDate: "05-08-2024",
    VehicleDetail: "Toyota Yaris 2004 - Code 3",
    Insurance: "Nyala Insurance",
    Premium: "ETB 3,400",
	status: "Checked",
  },
  {
    firstName: "Abebe",
    fathersName: "beso",
    grandFathersName: "bela",
    InspectionDate: "05-08-2024",
    VehicleDetail: "Toyota Yaris 2004 - Code 3",
    Insurance: "Nyala Insurance",
    Premium: "ETB 3,400",
	status: "Not Checked",
  },
  {
    firstName: "Abebe",
    fathersName: "beso",
    grandFathersName: "bela",
    InspectionDate: "05-08-2024",
    VehicleDetail: "Toyota Yaris 2004 - Code 3",
    Insurance: "Nyala Insurance",
    Premium: "ETB 3,400",
	status: "Not Checked",
  },
  {
    firstName: "Abebe",
    fathersName: "beso",
    grandFathersName: "bela",
    InspectionDate: "05-08-2024",
    VehicleDetail: "Toyota Yaris 2004 - Code 3",
    Insurance: "Nyala Insurance",
    Premium: "ETB 3,400",
	status: "Checked",
  },
  {
    firstName: "Abebe",
    fathersName: "beso",
    grandFathersName: "bela",
    InspectionDate: "05-08-2024",
    VehicleDetail: "Toyota Yaris 2004 - Code 3",
    Insurance: "Nyala Insurance",
    Premium: "ETB 3,400",
	status: "Not Checked",
  },
  {
    firstName: "Abebe",
    fathersName: "beso",
    grandFathersName: "bela",
    InspectionDate: "05-08-2024",
    VehicleDetail: "Toyota Yaris 2004 - Code 3",
    Insurance: "Nyala Insurance",
    Premium: "ETB 3,400",
	status: "Not Checked",
  },
  {
    firstName: "Abebe",
    fathersName: "beso",
    grandFathersName: "bela",
    InspectionDate: "05-08-2024",
    VehicleDetail: "Toyota Yaris 2004 - Code 3",
    Insurance: "Nyala Insurance",
    Premium: "ETB 3,400",
	status: "Not Checked",
  },
  {
    firstName: "Abebe",
    fathersName: "beso",
    grandFathersName: "bela",
    InspectionDate: "05-08-2024",
    VehicleDetail: "Toyota Yaris 2004 - Code 3",
    Insurance: "Nyala Insurance",
    Premium: "ETB 3,400",
	status: "Not Checked",
  },
  {
    firstName: "Abebe",
    fathersName: "beso",
    grandFathersName: "bela",
    InspectionDate: "05-08-2024",
    VehicleDetail: "Toyota Yaris 2004 - Code 3",
    Insurance: "Nyala Insurance",
    Premium: "ETB 3,400",
	status: "Not Checked",
  },
  {
    firstName: "Abebe",
    fathersName: "beso",
    grandFathersName: "bela",
    InspectionDate: "05-08-2024",
    VehicleDetail: "Toyota Yaris 2004 - Code 3",
    Insurance: "Nyala Insurance",
    Premium: "ETB 3,400",
	status: "Not Checked",
  },
]);
</script>
<template>
	<DefaultPage placeholder="Search For a Member">
		<template #more>
			<div class="flex gap-2 justify-end items-center">
				<Button  @click.prevent="openModal('addClient', row)" type="primary" class="flex items-center gap-2">
					<!-- <i v-html="icons.plus" /> -->
					New Inspection
				</Button>
				<!--<Button class="border border-priamry text-primary flex items-center gap-2">
					<i v-html="icons.import" />
					Import Members
				</Button>-->
			</div>
		</template>
   <Table
	   :headers="{
		    head: ['Customer Name', 'Inspection Date', 'Vehicle Detail', 'Insurance', 'Premium', 'Status', 'actions'],
			row: ['customerName', 'InspectionDate', 'VehicleDetail', 'Insurance', 'Premium', 'status'],
			}"
		:rowCom="Status_row" 
		  :rows="entries"

      :Fallback="TableRowSkeleton"
	 >
	
	  </Table>
	 
	</DefaultPage>
</template>